### ISSUE TITLE
Process with command "aspell --encoding utf-8 -a --lang=en_US" has failed running with exit code 1 on Windows

### ISSUE THREAD

**Issue by AmilaPriyankara** [tigitz/php-spellchecker#45]
when I create execute of aspell its throw an exception

$spell = Aspell::create();
$response = $spell->check('mispell', ['en_US']);
logger(print_r($response, true));

![image](https://user-images.githubusercontent.com/97216934/176908951-f08e5011-7567-4234-8bd4-33153905c4a0.png)

![image](https://user-images.githubusercontent.com/97216934/176909250-432984f7-6c4b-4cea-a7de-71ce54563a0e.png)

![image](https://user-images.githubusercontent.com/97216934/176909417-36c53be0-322d-4a96-87d9-404707474990.png)

![image](https://user-images.githubusercontent.com/97216934/176909489-cbb2d6da-0906-4997-b7cf-e21b7e1ff86c.png)

![image](https://user-images.githubusercontent.com/97216934/176909711-5ed90580-3f79-48e0-968d-ef4bfeb90350.png)

**PHP 8:
Window 10
Laravel 9
xampp**

**Comment by tigitz** [comment]
Hello @AmilaPriyankara, thanks for you report.

I haven't tested the lib on windows to be honest, so I'll try to blindly debug it with you.

In tinker, instead of 
![image](https://user-images.githubusercontent.com/1524501/177009912-74eba969-a124-4b00-89e9-6127fac1b3ed.png)
Could you try `var_dump(iterator_to_array($response)))`

Also when testing the command line directly, could you try `echo 'mispell' | aspell --encoding=utf-8 -a --lang=en_US` as it's what is actually executed in the background.

Let me know the output for both please.

**Comment by tigitz** [comment]
Digging a little further, according to https://superuser.com/questions/1496150/configuring-aspell-to-support-utf-8-encoded-texts it seems like `--encoding` is only supported in `aspell 0.60` which is not available on windows.

I'm unsure on how to circumvent the problem to support windows user right now. If you tried anything on your hand, let me know.

**Comment by hugomatheuss** [comment]
I think when you are on Windows, you should try to use the wsl2, then you can run sudo apt-get install -y aspell aspell-en and use this fine.

**Comment by tigitz** [comment]
Closing as project requires aspell < 0.60, you could either use WSL, use [Hunspell ](https://community.chocolatey.org/packages/hunspell.portable) instead, or use an up to date [aspell](https://github.com/iquiw/aspell-binary?tab=readme-ov-file)
